# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BuildAndDeploy
on:
  push:
    # 只有当推送代码到mater分支才执行
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout repository code
        uses: actions/checkout@v2
      # 下载 git submodule
      - name: Download Git
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:10
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      # 修改文件的appenv
      - name: Modify File
        run: |
          sed -i "0,/appenv/{s/appenv.*/appenv\x20=\x20'app';/}" ./src/api/appenv.js
          cat ./src/api/appenv.js
      # 安装依赖并且打包静态文件
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true
      # 部署应用到服务器
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}