# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
  push:
    # 只有当推送代码到mater分支才执行
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout repository code
        uses: actions/checkout@v2
      # 下载 git submodule
      - name: Download Git
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:10
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      # npm install
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true