# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm i
    - run: npm run build

	# 部署应用到服务器
	# - name: Deploy
	# 	uses: easingthemes/ssh-deploy@v2.0.7
	# 	env:
	# 		SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
	# 		ARGS: "-avz --delete"
	# 		SOURCE: "wood-judge-front/"
	# 		REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
	# 		REMOTE_USER: ${{ secrets.REMOTE_USER }}
	# 		TARGET: ${{ secrets.TARGET }}

